spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI}

jwt:
  audience: ${AUTH_INTERNAL_AUDIENCE}

auth:
  service:
    url: ${AUTH_SVC_URI}
