spring:
  datasource:
    url: ${DB_URL:localhost:5432}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8083/oauth/jwks}

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE:internal-services}
